[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
    "@limitbreak/creator-token-standards/=lib/creator-token-standards/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc721a/=lib/ERC721A/",
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
